export const metadata = {
  title: "Pricing Page",
  description: "Generated by Daza",
};

export default function PricingPage() {
  return (
    <div>
      <span className="text-7xl">Pricing Page</span>
    </div>
  );
}
