export const metadata = {
  title: "Contact Page",
  description: "Generated by Daza",
};

export default function ContactPage() {
  return (
    <div>
      <span className="text-7xl">Contact Page</span>
    </div>
  );
}
