import { Metadata } from "next";

export const metadata: Metadata = {
  title: "About Page",
  description: "Generated by Daza",
  keywords: ['Information', 'Daza']
};

export default function About() {
  return <span className="text-7xl">About Me</span>;
}
